"""empty message

Revision ID: 332b2ddca0e7
Revises: 4780d9aefed3
Create Date: 2021-03-25 18:53:40.572893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332b2ddca0e7'
down_revision = '4780d9aefed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'todos', ['label'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='unique')
    # ### end Alembic commands ###
